# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e7a7e7e65b636c1409e99a25ccb8844b240726b8d77bcb01d5a87f659cc5e452595c6a46873b3a47c4398868445eeb73e0ab1635aebc7fbae39c774adbff531

test:
  secret_key_base: b7b1f1d15713d1f3d38658574bf317d0e9b61317d97bc2025544291de2fcf049a1c56c09c7999f31cbfc0e0db0c3da3246a0679914ed14c8a6ee4f7cd7fbc3a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
